name: Uradhura

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      job:
        description: 'Deploy manually'
        required: true
        default: 'deploy'

env:
  CARGO_TERM_COLOR: always
  PROJECT_NAME: ${{ github.event.repository.name }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  DEPLOYMENT_HOST: ${{ secrets.DEPLOYMENT_HOST }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release && strip target/release/$PROJECT_NAME

  deploy:
    runs-on: ubuntu-latest

    #needs: build

    environment:
      name: dev

    if: ${{ github.event.inputs.job == 'deploy'}}

    steps:
      - name: setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod -R 700 ~/.ssh
          cd ~/.ssh

          echo "$SSH_PRIVATE_KEY\n" > id_rsa
          chmod 400 id_rsa

          ssh-keyscan $DEPLOYMENT_HOST > known_hosts
          chmod 644 known_hosts      

      - name: rsync binary
        run: rsync -a target/release/$PROJECT_NAME $SSH_USER@$DEPLOYMENT_HOST:/home/$SSH_USER/uradhura/

      - name : restert uradhura.service
        run: ssh $SSH_USER@$DEPLOYMENT_HOST "systemctl --user restart uradhura.service"
  
  release:    
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/$PROJECT_NAME
